fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "sciesiek@wp.pl"
        sender_name: "sciesiek"
    registration:
        confirmation:
            enabled: false
            template: '@FOSUser/Registration/email.txt.twig'